### ISSUE TITLE
undefined symbol: Float32_BoxCoxLambdaGuerrero

### ISSUE THREAD

**Issue by AruparnaMaity** [Nixtla/coreforecast#27]
I was setting this up in GCP Linux system. I encountered the following error:

`AttributeError: /opt/conda/lib/python3.7/site-packages/coreforecast/lib/libcoreforecast.so: undefined symbol: Float32_BoxCoxLambdaGuerrero`

Is it an issue with the ".so" file? Please let me know what extra details I should share. Attaching a screenshot of the error.
![image](https://github.com/Nixtla/coreforecast/assets/41180444/22e9789b-16fc-4587-9b04-4260619dafac)

Regards,
Aruparna

**Comment by jmoralez** [comment]
Hey. How did you install the packages?

**Comment by AruparnaMaity** [comment]
> Hey. How did you install the packages?

I installed the package by the usual way:
`pip install coreforecast`

**Comment by jmoralez** [comment]
coreforecast requires python>=3.8 (except for v0.0.1) and neuralforecast doesn't require it, except for the dev version, which requires coreforecast>=0.0.6. So you must've done something different.

**Comment by jmoralez** [comment]
Closing due to lack of response. Feel free to reopen with more information.
