### ISSUE TITLE
Rolling Quantiles

### ISSUE THREAD

**Issue by joshdunnlime** [Nixtla/coreforecast#7]
Rolling/expanding quantiles are super slow in pandas, as you might expect. If I am reading the code correctly, there is IQR and rolling MAD, but no rolling quantiles. There is already the function in C to create quantiles. Can this be exposed in the python package?

There is also the option of algorithmically superior operations. Here are some examples:
Heap based moving median: https://aakinshin.net/posts/partitioning-heaps-quantile-estimator/

And approximate moving median/quantiles:
https://aakinshin.net/posts/mp2-quantile-estimator/
https://aakinshin.net/posts/partitioning-heaps-quantile-estimator2/

**Comment by jmoralez** [comment]
Hey @joshdunnlime, are you looking to use these directly or in mlforecast?

**Comment by jmoralez** [comment]
We'll add mlforecast support in the next release. If you try them here please let us know how it goes, they're not heavily optimized but should be around 20x faster than pandas.
